
<?php View::content()?>
<center class="page-header">
	<h2>Ingreso al Sistema</h2>
	<h2><small>Introduzca su nombre de usuario y contraseña</small></h2>
</center>
<?php echo Form::open("","POST","class=\"form-horizontal\" role=\"form\" ")?>

  <div class="form-group">
    <label for="Nombre de Usuario" class="col-sm-2 control-label">Nombre de Usuario</label>
    <div class="col-sm-10">
      <input type="text" maxlength="20" name="nombre_usuario" class="form-control" id="nombre_usuario" placeholder="Nombre de Usuario">
    </div>
  </div>
  <div class="form-group">
    <label for="Contraseña" class="col-sm-2 control-label">Contraseña</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="clave" name="clave" placeholder="Contraseña">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    	<?php echo Form::submit("Entrar","class=\"btn btn-primary\" ")?>
    </div>
  </div>
<?php echo Form::close()?>
<br>
<?php if(Auth::is_valid()):?>
	<?php echo Html::link("usuario/perfil/".Auth::get("id"),"Mi Perfil","class=\"btn btn-primary center-block\" " ) ?>
	<?php if (Auth::get("admin")==1): ?>
		<?php echo Html::link("usuario/nuevo/","Nuevo Usuario","class=\"btn btn-primary center-block\" " ) ?>
	<?php endif;?>
<?php endif; ?>
		