
<?php View::content()?>
<center>
		<h3>Nuevo Usuario</h3>
		<h2><small>Introducir datos del nuevo usuario</small></h2>
</center>
<?php echo Form::open("","POST"," class=\"form-horizontal\" role=\"form\" ")?>
  <div class="form-group">
    <label for="nombre" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
      <input type="text" maxlength="20" class="form-control" name="usuario[nombre]" id="nombre" placeholder="Nombre">
    </div>
  </div>
  <div class="form-group">
    <label for="apellido" class="col-sm-2 control-label">Apellido</label>
    <div class="col-sm-10">
      <input type="text" maxlength="20" class="form-control" name="usuario[apellido]" id="apellido" placeholder="Apellido">
    </div>
  </div>
  <div class="form-group">
    <label for="cedula" class="col-sm-2 control-label">Cédula</label>
    <div class="col-sm-10">
      <input type="text" maxlength="9" class="form-control" name="usuario[cedula]" id="cedula" placeholder="Cédula">
    </div>
  </div>
  <div class="form-group">
    <label for="nombre_usuario" class="col-sm-2 control-label">Nombre de Usuario</label>
    <div class="col-sm-10">
      <input type="text" maxlength="20" class="form-control" name="usuario[nombre_usuario]" id="nombre_usuario" placeholder="Nombre de Usuario">
    </div>
  </div>
  
    <div class="form-inline">
    <label for="nombre_usuario" class="col-sm-2 control-label">Contraseña</label>
   
      <input type="password" class="form-control col-sm-3" name="usuario[clave]" id="clave" placeholder="Contraseña">
      <input type="password" class="form-control col-sm-3" name="usuario[clave2]" id="clave2" placeholder="Repetir Contraseña">
    </div>
  </div>
  <br>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-20 ">
      <button type="submit" class="btn btn-primary pull-rigth">Crear</button>
    </div>
  </div>
</form>
	