
<?php View::content()?>
<?php if(!empty($usuario)):?>
	
	
	<div class="clearfix"></div>

	<center >
		<h3><?php echo ucfirst($usuario->nombre)." ".ucfirst($usuario->apellido) ?></h3>
	</center>
	
	<div class="container">
		<div class="row">
		  <div class="col-md-4"><b>Número de Cédula</b></div>
		  <div class="col-md-4"><?php echo $usuario->cedula ?></div>
		</div>
		<div class="row">
		  <div class="col-md-4"><b>Nombre de Usuario</b></div>
		  <div class="col-md-4"><?php echo $usuario->nombre_usuario ?></div>
		</div>
		<div class="row">
		  <div class="col-md-4"><b>Usuario Administrador</b></div>
		  <?php if($usuario->admin == 1): ?>
		  	<div class="col-md-4"><?php echo "Es Administrador" ?></div>
		  <?php else: ?>
		  	<div class="col-md-4"><?php echo "No posee privilegios de Administrador" ?></div>
		  <?php endif;?>
		</div>
		<br>
		
		<div class="clearfix"></div>
	</div>
<?php endif;?>
		